### ISSUE TITLE
PropertyChanged notification for HasErrors

### ISSUE THREAD

**Issue by seanterry** [Fody/Validar#4]
Try as I might, I can't seem to get Validar.Fody and PropertyChanged.Fody to play nicely together. Everything works great except for triggering a PropertyChanged notification on the HasErrors property.

**Comment by BrunoJuchli** [comment]
@SimonCropp 
Hi Simon, thanks for the great work, as always :-)
Running `Propertychanged` after `Validar` does not work in case in case the `ViewModel` has `[ImplementPropertyChanged]`, since, of course, `Validar` expects the `ViewModel` to implement `INotifyPropertyChanged` - and when `Validar` is run before `PropertyChanged`, the `ViewModel` does not implement ÌNotifyPropertyChanged` *yet*.

Of course this can be worked-around by manually implementing `INotifyPropertyChanged` on the `ViewModel`. However, my testing suggests that even in the case of `Validar` before `PropertyChanged` there's no `PropertyChanged` notification for `HasErrors` taking place.

Having a look at the code which is generated by `Validar`, this makes complete sense. This is what `Validar` weaves into `ViewModel`:

    bool INotifyDataErrorInfo.HasErrors
    {
        get
        {
            return ((INotifyDataErrorInfo)this.validationTemplate).HasErrors;
        }
    }

`PropertyChanged` is incapable of tracking changes for this and thus not weave them.

**Comment by BrunoJuchli** [comment]
btw. is there another, .. better.. approach to disable a "save" or "ok" button when the validation fails?

**Comment by BrunoJuchli** [comment]
The use case i wanted to have `HasErrors` property changed notification was using `IsEnabled="{Binding HasErrors, Converter={...}}" on a save button.
I've just stumbled upon this: http://stackoverflow.com/a/18651331/684096

Will have to check whether i can use this as a workaround. Will report back once i've tried it out (should get a chance during the course of this week).

**Comment by BrunoJuchli** [comment]
I couldn't get "the workaround" working as i wanted it to. So i'm still looking for a way to bind to the `INotifyDataErrorInfo.HasErrors` property with property-changed notification.

**Comment by SylwesterZarebski** [comment]
@BrunoJuchli You can use explicit validation template field in your viewmodel:
```c#
Validation.ValidationTemplate validationTemplate;
[DependsOn("Property1", "Property2")]
public bool HasErrors
{
    get { return this.validationTemplate.HasErrors; }
}
```
Above code uses Fody.PropertyChanged with Fody.Validar.

If You also use Caliburn.Micro, then You could use `Can*` convention like `CanButtonName` to simplify binding (avoid explicit `IsEnabled=...`)

**Comment by BrunoJuchli** [comment]
@SylwesterZarebski 
Thanks. The `[DependsOn]` having to list all properties manually is a serious down-side, though. This is far from refactor friendly - it introduces code which is very likely to cause a bug in the future.

**Comment by SylwesterZarebski** [comment]
True, but if You use C#6 (VS2015) You could use it with `nameof()` construct and be refactor friendly :).

**Comment by BrunoJuchli** [comment]
@SylwesterZarebski until you add a new property....
